# 网站的基本信息
site:
  tab: 我的博客 # 浏览器标签栏上显示的文本
  title: 我的博客 # 网站的标题
  description: nodca 的个人博客，分享技术学习笔记、编程经验、项目开发心得和生活感悟。 # 网站的描述，用于SEO等
  language: zh # 网站的语言，例如 "en" 是英文
  favicon: /favicon.ico # 网站的图标，用于浏览器标签栏和其他地方显示
  theme: # 更多主题 https://daisyui.com/docs/themes/
    light: winter # 主题的浅色模式
    dark: dracula # 主题的深色模式
    code: github-dark # 代码块的主题 https://expressive-code.com/guides/themes/
  date_format: YYYY年MM月DD日 # 日期格式设置，支持自定义格式
  blog: # 博客相关配置
    pageSize: 8 # 每页显示的文章数量
  menu: # 菜单配置
    - id: home # 菜单项的唯一标识符
      text: 首页 # 菜单项显示的文本
      href: / # 菜单项链接的地址
      svg: "material-symbols:home-outline-rounded"
      target: _self
    - id: about
      text: 关于
      href: /about
      svg: "material-symbols:info-outline-rounded"
      target: _self
    - id: blog
      text: 博客
      href: /blog
      svg: "material-symbols:book-2-outline-rounded"
      target: _self
      subItems:
        - id: all
          text: 全部文章
          href: /blog
          svg: "material-symbols:ink-pen-outline-rounded"
          target: _self
    - id: project
      text: 项目
      href: /project
      svg: "material-symbols:code-blocks-outline"
      target: _self
    - id: friend
      text: 友链
      href: /friend
      svg: "material-symbols:supervisor-account-outline-rounded"
      target: _self
    - id: shortlink
      text: 短链工具
      href: "https://s.cyb1.org"
      target: _blank
      svg: "material-symbols:link"

# 用户的个人信息
user:
  name: nodca # 用户名
  site: "https://blog.cyb1.org" # 用户的网站链接
  avatar: /profile.jpg # 用户头像路径
  sidebar: # 侧边栏配置
    social:
      - href: "https://github.com/nodca"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
  footer:
    social:
      - href: "https://github.com/nodca"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
